### ISSUE TITLE
[Feature idea] Custom commands

### ISSUE THREAD

**Issue by fmauch** [fzi-forschungszentrum-informatik/robot_folders#26]
We could provide an entry point where users could provide their custom commands by configuring them as simple strings. This way users can add specific functionality they need for *their* daily business without going all the effort of adding a new `click` command and having this integrated.

## Configuration
In the config file there could be a section for this

```yaml
custom_commands: {
  - vcs_pull: cd $ROB_FOLDERS_ROOT_ENV && vcs pull colcon_ws/src
}
```

## Command
The command could be either added to toplevel, so the above would add a `fzirob wcs_pull` command or they could all be assembled behind a `custom` command resultin in `fzirob custom vcs_pull`.
